function SSHyClient() {}

SSHyClient = {
    // Global Defines
    MSG_SERVICE_REQUEST: 5,
    MSG_SERVICE_ACCEPT: 6,

    MSG_KEX_INIT: 20,
    MSG_NEW_KEYS: 21,
    MSG_KEXDH_INIT: 30,
    MSG_KEXDH_REPLY: 31,

    MSG_USERAUTH_REQUEST: 50,
    MSG_USERAUTH_FAILURE: 51,
    MSG_USERAUTH_SUCCESS: 52,
    MSG_USERAUTH_BANNER: 53,

    MSG_CHANNEL_OPEN: 90,
    MSG_CHANNEL_OPEN_SUCCESS: 91,
    MSG_CHANNEL_OPEN_FAILURE: 92,
    MSG_CHANNEL_DATA: 94,
    MSG_CHANNEL_REQUEST: 98,
    MSG_CHANNEL_SUCCESS: 99,

    WINDOW_SIZE: 1048576, // from openssh
    MAX_PACKET_SIZE: 16384
}

SSHyClient.cipher_mode = {
    AES_CBC: 2,
    AES_CTR: 6
}
